---
title: "I'm Starting a Live Stream for R Tutorials"
author: Colin Quirk
date: '2020-07-30'
slug: starting-a-livestream
categories: [misc]
tags: []
---

I am starting a [youtube channel](https://www.youtube.com/channel/UC-vtwz7ueU2dtnHk5e-WblA) for R tutorials! Of course, there are a million tutorial channels that already exist, so why is this one any different? The goal is to give the tutorials live on stream, so that viewers have the chance to interact and ask questions similar to if it was an in person workshop. It also means that the content will be messy just like real coding. I view this as a positive as it implicitly teaches how to understand error messages and debug code. Of course, this is not the only live stream for code either. David Robinson for example does a live stream for Tidy Tuesday each week. There are other streamers on twitch who stream themselves working on open source projects. But, I think the area of live weekly tutorials are under explored. Right now, I am planning on having my streams from 5pm to 6pm Chicago time (CDT). The stream will not be going over total basics and instead will focus on showing new things to people who know a little bit of R but are perhaps not totally confident with it.

Why am I doing this? I run a lot of tech workshops at my university. In fact, I started a student group with the goal of bringing together a community of students who could work together when they get stuck on technical problems. Thanks to COVID, this group is currently on hiatus and sadly may not be able to fully pick back up before I have finished my time at UChicago. Graduate students are also a difficult population to try to plan events for because we are all very busy, so while we had a solid foundation of students it was hard to grow the group. Because of this, my attention is turning towards trying to create a similar community that is open to everyone!

If this interests you at all, I hope you will stop by! You can request topics with [this form](https://forms.gle/og6wz5cHoo5GyV7x7). If you can't make it live, the VODs are available on my channel. I hope to see you there!
